import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";
import { execSync } from "child_process";

const DEPLOYMENTS_JSON = path.resolve(__dirname, "../../../../deployments.json");
const DEPLOYMENTS_TS = path.resolve(__dirname, "../../../../web/src/config/deployments.ts");
const CRATE_DIR = path.resolve(__dirname, "../..");
const PVM_BINARY = path.resolve(CRATE_DIR, "target/covered-call.release.polkavm");

function updateDeployments(key: string, address: string) {
	let data: Record<string, string | null> = { evm: null, pvm: null };
	try {
		data = JSON.parse(fs.readFileSync(DEPLOYMENTS_JSON, "utf-8"));
	} catch {
		// File doesn't exist yet
	}
	data[key] = address;

	fs.writeFileSync(DEPLOYMENTS_JSON, JSON.stringify(data, null, 2) + "\n");

	const fmt = (v: string | null) => (v === null ? "null" : `"${v}"`);
	const keys = Object.keys(data) as string[];
	const entries = keys.map((k) => `\t${k}: ${fmt(data[k])},`).join("\n");
	const typeFields = keys.map((k) => `${k}: string | null`).join("; ");
	const ts = `// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { ${typeFields} } = {
${entries}
};
`;
	fs.writeFileSync(DEPLOYMENTS_TS, ts);
}

async function main() {
	console.log("Building CoveredCall (PVM-Rust)...");
	execSync("cargo build --release --bin covered-call", {
		cwd: CRATE_DIR,
		stdio: "inherit",
		env: { ...process.env, CARGO: undefined, RUSTUP_TOOLCHAIN: "nightly" },
	});

	console.log("Deploying CoveredCall (PVM-Rust)...");

	const [walletClient] = await hre.viem.getWalletClients();
	const publicClient = await hre.viem.getPublicClient();

	const raw = fs.readFileSync(PVM_BINARY);
	const bytecode = `0x${raw.toString("hex")}` as `0x${string}`;

	const hash = await walletClient.deployContract({
		abi: [],
		bytecode,
	});

	const receipt = await publicClient.waitForTransactionReceipt({
		hash,
		timeout: 120_000,
	});

	if (!receipt.contractAddress) {
		throw new Error(`Deploy tx ${hash} did not create a contract`);
	}

	console.log(`CoveredCall deployed to: ${receipt.contractAddress}`);
	updateDeployments("coveredCall", receipt.contractAddress);
	console.log("Updated deployments.json and web/src/config/deployments.ts");
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
