// Auto-generated by contract deploy scripts — do not edit manually
export const deployments: { evm: string | null; pvm: string | null; coveredCall: string | null } = {
	evm: "0xc01ee7f10ea4af4673cfff62710e1d7792aba8f3",
	pvm: "0x970951a12f975e6762482aca81e57d5a2a4e73f4",
	coveredCall: "0xec407d71097bb75dacceaa816ef9b35cc5c9bdfd",
};
